### PR TITLE
Created Remote engine for Glados TTS

### PR DESCRIPTION
**Pull request by eternalliving**
I believe this is similar to the testing server glados.2022.us. 
It enables the engine running on a different machine and for the voice to be collected with curl.

I've also created the code for the main glados-voice-assistant and my hope is this will allow the Raspberry Pi's to stay up to date with all the other changes. Hopefully the raspberry branch can be remove in favour of this setup.

I have a machine I would be willing to have this run on for the foreseeable future as well.

### CODE REVIEW

**Comment by nerdaxic** [comment]
I would like to use the same TTS glados engine function in the local and remote versions. As If we do changes to it, no need to write them in multiple files.

Also I would like it to save the wav file in cache in similar way the voice assistant does - currently if five people ask for samples they might get each others output.wav file?

Caching would make service faster for common sentences. 
I am planning to make web interface for this, so I should also be able to host.

**Comment by eternalliving** [comment]
Good thoughts, I didn’t want to interrupt too much on your main script and so thought creating extra options for executing would be better.

So have all setups either host their own Glados-tts server or have them connect to one remotely, instead of running it directly in the same python script as it currently is?

Still utilize curl for the requests? A engine cache is a good idea, how do you decide what to cache and what to leave out? We can certainly use the line in the name to a certain point, long responses may run into troubles with file name lengths. 

Would need to make sure the local assistant doesn’t also keep a cache if it’s running a local tts engine. 

I’m happy to put this together, just need to know the desire for the overall flow.

**Comment by nerdaxic** [comment]
1. I wish there to be a setting in the coming glados_settings.yaml file: "External TTS API", which contains the address of the external tts.
2. If the setting is not empty, don't use local TTS, which would be the default option.
3. I'd say external engine caches everything
4. Every time file is loaded from cache, the engine could run "touch" command on the wave file updating its "last modified" time.
5. Have some other utility script go through the cache folder now and then removing "files older than"
6. Still utilize curl, can be changed. I used it because I found it quick n easy, also to run as subprocess in the background.
7. Can have additional setting in the settings file to turn off local cache if using external TTS with cache.
8. Use current settings file, add the new lines to sample file. I will move them to yaml once I get around to it.
9. Thank you

**Comment by eternalliving** [comment]
Alright, I think I met list...
1. check
2. check
3. check
4. check
5. needs developing. I wasn't sure whether to make a cron script, or how else to have it only run now and then.
6. check - very easy and nice, although I'm not sure about error handling at the moment? Wrong address it seems to keep retrying?
7. I think you always want local cache, unless it's within your own network, in which you can set the CACHE variable in the engine to false.
8. settings file updated
9. you're welcome :)

The engine now is one script. If it is run directly it will also load the api server and enable caching for everything less then 200 characters. If we want to support more characters then I think hashing the line before storing would be an option.
I've updated the main glados-voice-assistant and will create a pull request with the changes to suit.

**Comment by nerdaxic** [comment]
10. Tested and confirmed working
11. Merged

**Pull request merged**
